spring:
  datasource:
    url: ${env.URL_DATABASE}
    username: ${env.USERNAME_DATABASE}
    password: ${env.PASSWORD_DATABSE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
